name: init-npm
description: 'Initialize the repo with npm and install all the dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '22.x'
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - name: Install TS Project dependencies
      shell: bash
      run: npm ci
    - name: Build project
      shell: bash
      run: npm run build
    # - name: Generate Prisma types from schema
    #   shell: bash
    #   run: npm run migration:generate-types
