import { Prisma } from '@prismaClient';
import type { components, operations } from '@src/openapi';
import { StagePrismaObject } from '@src/stages/models/models';

type JobModel = components['schemas']['jobResponse'];
type JobCreateModel = components['schemas']['createJobPayload'];
type JobCreateResponse = components['schemas']['createJobResponse'];
type JobGetParams = components['parameters'];
type JobFindCriteriaArg = operations['findJobs']['parameters']['query'];

// Generated by Copilot
/**
 * Generic type for Job Prisma objects with configurable stage inclusion
 * @template TIncludeStages - Whether to include stages in the result
 */
type JobPrismaObject<TIncludeStages extends boolean = boolean> = Prisma.JobGetPayload<{
  include: { stage: TIncludeStages };
}>;

/**
 * Job Prisma object with optional stages array
 * @deprecated Use JobPrismaObject<true> instead
 */
type JobPrismaObjectWithStages = JobPrismaObject<true> & { stage?: StagePrismaObject[] };

export type { JobModel, JobCreateModel, JobCreateResponse, JobGetParams, JobFindCriteriaArg, JobPrismaObject, JobPrismaObjectWithStages };
