apiVersion: v2
name: jobnik-manager
description: A Helm chart for jobnik-manager service
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: mc-labels-and-annotations
    version: 0.7.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    alias: mcLabelsAndAnnotations
