global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ''

mclabels:
  component: backend
  owner: infra
  partOf: jobnik
  prometheus:
    enabled: true
    
enabled: true
environment: development
replicaCount: 1
revisionHistoryLimit: 5 # Amount of revisions we keep
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: false

nameOverride: ""
fullnameOverride: ""

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

podAnnotations: {}

extraVolumes: []

extraVolumeMounts: []

extraEnvVars: []

command: []
args: []
# command: [ "/bin/sh", "-c", "--" ]
# args: [ "while true; do sleep infinity; done;" ]

sidecars: []

cloudProvider:
  dockerRegistryUrl: 
  imagePullSecretName: ''
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: jobnik-manager
  # If commented, appVersion will be taken. See: _helpers.tpl
  # tag: 'latest'
  pullPolicy: IfNotPresent

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

  configManager:
    offlineMode: false
    name: 'infra-jobnik-manager'
    version: 'latest'
    serverUrl: 'http://localhost:8080/api'
  
dbConfig:
  host: localhost
  database: jobnik
  port: 5432
  useExternalSecret: false
  secretName: ''
  sslAuth:
    enabled: false
    certFileName: cert.pem
    keyFileName: key.pem
    caFileName: ca.crt
staleTasksSweeperCron:
  enabled: true
  schedule: '0 0 * * *' # every day at midnight
task:
  staleTaskThresholdInMinutes: 1440 # 24 hours

resources:
  enabled: true
  value:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 250Mi

route:
  enabled: true
  path: /
  host: 
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
  rewriteTarget: ''
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    useCerts: false
    certificate: ''
    key: ''
    caCertificate: ''

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
